[[feeds]]
url = "https://feed.eugenemolotov.ru/?action=display&bridge=Twitter&context=By+username&u=energeticbark&format=Atom"
pfp = "https://pbs.twimg.com/profile_images/1365907443268669441/jUrM7EVT_normal.jpg"
webhook = ""

[cache]
cache = ["https://twitter.com/energeticbark/status/1526641075170967553", "https://twitter.com/energeticbark/status/1523178499095232512", "https://twitter.com/energeticbark/status/1523176470385881089", "https://twitter.com/energeticbark/status/1516899644495831042", "https://twitter.com/grahamlucario/status/1514786902657802252"]
